my_project12_v1/accounts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import (ChangeProfileView, LoginView, LogoutView, SignupView,
                    profile)

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='blog-home'),
    path("login/", LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/<pk>/', ChangeProfileView.as_view(), name='profile_update'),
]

my_project12_v1/my_project12_v1/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

my_project12_v1/projects/urls.py
from django.urls import path

from . import views
from .views import (ApplicationListView, CreateApplicationView,
                    CreateProjectView, ProjectDeleteView, ProjectDetailView,
                    ProjectListView, RecomProjectListView,
                    UpdateApplicationView, UpdateProjectView,
                    UserApplicationListView, UserProjectListView,
                    UserProjectsApplicationsListView,
                    CreatePositionView,
                    )

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='list_projects'),
    path('recom/', RecomProjectListView.as_view(), name='recom_list_projects'),
    path('user/<str:username>/', UserProjectListView.as_view(), name='user_list_projects'),
    path('project/new/', CreateProjectView.as_view(), name='project_create'),
    path('position/new/', CreatePositionView.as_view(), name='position_create'),
    path('project/<pk>/update/', UpdateProjectView.as_view(), name='project_update'),
    path('project/<pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('search/', views.search_projects, name='project_search'),
    path('applications/all/', ApplicationListView.as_view(), name='list_applications'),
    path('applications/new/<slug>/<pk>/', CreateApplicationView.as_view(), name='application_create'),
    path('applications/user/<pk>/', UserApplicationListView.as_view(), name='user_list_applications'),
    path('applications/touser/<pk>/', UserProjectsApplicationsListView.as_view(), name='applications'),
    path('applications/status/update/<pk>/', UpdateApplicationView.as_view(), name='application_update'),
    path('applications/notifications/', views.view_notifications, name="notifications"),
]

my_project12_v1/templates/index.html
{% extends 'layout.html' %}
{% block content %}

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h3>Projects by skills </h3>
        <hr>
        <ul class="circle--filter--list">
          <li><a class="" href="projects/search/?q=javascript">JavaScript</a></li>
          <li><a class="" href="projects/search/?q=sql">SQL</a></li>
          <li><a class="" href="projects/search/?q=python">Python</a></li>
          <li><a class="" href="projects/search/?q=css">CSS</a></li>
          <li><a class="" href="projects/search/?q=design">Design</a></li>
          <li><a class="" href="projects/search/?q=ux">UX/User experience</a></li>
        </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="{% url 'projects:project_create' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>
    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <ul class="circle--filter--list">
          <li><a class="selected">All Needs</a></li>
          {% for object in all_projects %}
            {% for position in object.position.all %}
              {% if position.position_status == False %}
                <li><a class='selected' href="{% url 'projects:project_detail' pk=object.pk %}">{{ position }} in {{ object }} is available</a></li>
                <p>Position requires: </p>
                  {% for skill in position.skills.all %}
                  <span>{{ skill }}</span>
                  {% endfor %}
                    <hr>
              {% endif %}
              {% if position.position_status == True %}
                <li><a>{{ position }} in {{ object }} is filled</a></li>
              {% endif %}
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
          </tr>
        </thead>
        <tbody>
          <tr class="clickable-row" data-href="project.html">
            <td>
            <td class="circle--cell--right">
              <span class="secondary-label"></span>
            </td>
          </tr>
            <td class="circle--cell--right">
              <span class="secondary-label"></span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

{% endblock %}

my_project12_v1/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Circle</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  {% block css %}
  {% endblock %}

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/global.js' %}"></script>


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <form action="{% url 'projects:project_search' %}" method="GET">
              <input type="text" placeholder="Search Projects:)" name='q'/>
            </form>
            <button>
              <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
            </button>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
              <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
              <li><a href="{% url 'projects:notifications' %}">Notifications</a></li>
              {% else %}
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              <li><a href="{% url 'accounts:login' %}">Log In</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
{% if messages %}
   {% for message in messages %}
      <div class="alert alert-warning">
          {{ message }}
      </div>
   {% endfor %}
{% endif %}  
{% block content %}{% endblock %}
{% block js %}
{% endblock %}
</body>
</html>