my_project12_v1/accounts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import (ChangeProfileView, LoginView, LogoutView, SignupView,
                    profile)

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='blog-home'),
    path("login/", LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/<pk>/', ChangeProfileView.as_view(), name='profile_update'),
]

my_project12_v1/my_project12_v1/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

my_project12_v1/projects/urls.py
from django.urls import path

from . import views
from .views import (ApplicationListView, CreateApplicationView,
                    CreateProjectView, ProjectDeleteView, ProjectDetailView,
                    ProjectListView, RecomProjectListView,
                    UpdateApplicationView, UpdateProjectView,
                    UserApplicationListView, UserProjectListView,
                    UserProjectsApplicationsListView,
                    CreatePositionView,
                    )

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='list_projects'),
    path('recom/', RecomProjectListView.as_view(), name='recom_list_projects'),
    path('user/<str:username>/', UserProjectListView.as_view(), name='user_list_projects'),
    path('project/new/', CreateProjectView.as_view(), name='project_create'),
    path('position/new/', CreatePositionView.as_view(), name='position_create'),
    path('project/<pk>/update/', UpdateProjectView.as_view(), name='project_update'),
    path('project/<pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('search/', views.search_projects, name='project_search'),
    path('applications/all/', ApplicationListView.as_view(), name='list_applications'),
    path('applications/new/<slug>/<pk>/', CreateApplicationView.as_view(), name='application_create'),
    path('applications/user/<pk>/', UserApplicationListView.as_view(), name='user_list_applications'),
    path('applications/touser/<pk>/', UserProjectsApplicationsListView.as_view(), name='applications'),
    path('applications/status/update/<pk>/', UpdateApplicationView.as_view(), name='application_update'),
    path('applications/notifications/', views.view_notifications, name="notifications"),
]

my_project12_v1/projects/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone



class Project(models.Model):
    '''A project model'''
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField(blank=True)
    slug = models.SlugField(max_length=100, unique=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    position = models.ManyToManyField(
        'Position', 
        blank=True,
        related_name='projects')
    project_status = models.BooleanField(default=False)
    project_timeline = models.TextField(max_length=200, blank=True)
    applicant_requirements = models.TextField(
                                            max_length=200,
                                            default='Applicants are required '
                                            'to be passionate about what they do'
                                            )


    def __str__(self):
        return self.title

    def slug(self):
        return slugify(self.title)    

    def get_absolute_url(self):
        return reverse('projects:project_detail', kwargs={'pk': self.pk})    

    class Meta:
        ordering = ['-date_posted']  
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'  

    
class Position(models.Model):
    '''A position model'''
    title = models.CharField(max_length=100, unique=True)
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE, 
        related_name='positions'
        )
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    position_status = models.BooleanField(default=False)
    skills = models.ManyToManyField(
        'accounts.Skill', 
        blank=True)

    def __str__(self):
        return self.title 

    def get_absolute_url(self):
        return reverse('projects:project_detail', kwargs={'pk': self.project.id})    

    class Meta:
        ordering = ['-date_posted']    


class Application(models.Model):
    '''An application model'''

    STATUS = (
        ('ACC', 'Accepted'),
        ('DEC', 'Declined'),
        ('AWA', 'Awaiting')
    )

    applicant = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='applicants'
    )     
    project = models.ForeignKey(
        Project, 
        on_delete=models.CASCADE,
        related_name='applied_project'
    )
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name='applied_position'
    )        
    status = models.CharField(
        choices=STATUS,
        max_length=3, default='AWA'
    )
    date_applied = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_applied']

    def __str__(self):
        return '{} application for {}\'s {} position'.format(self.applicant, self.project, self.position )   

my_project12_v1/projects/forms.py
from django import forms

from .models import Position, Project


class ProjectForm(forms.ModelForm):
    '''A project form'''
    class Meta:
        model = Project
        fields = [
            'title',
        ]

class PositionForm(forms.ModelForm):
    '''A position form'''
    class Meta:
        model = Position
        fields = [
            'title',
            'project',
        ]

my_project12_v1/projects/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse
from django.views import generic
from notifications.signals import notify
from django.urls import reverse_lazy

from accounts.models import Profile, Skill, User

from .models import Application, Position, Project
from django.forms.models import inlineformset_factory


class ProjectListView(generic.ListView):
    '''Project list view'''
    model = Project
    template_name = 'all_projects.html'
    context_object_name = 'projects'
    ordering = ['-date_posted']
    paginate_by = 3


class RecomProjectListView(generic.ListView):
    '''Recommended projects list view'''
    model = Project
    template_name = 'recom_projects.html'
    context_object_name = 'recom_projects'
    ordering = ['-date_posted']
    paginate_by = 3

    def get_queryset(self):
        profile = self.request.user.profile
        user_skills = Skill.objects.filter(profile=profile)
        return Project.objects.filter(
            position__skills__in=user_skills
            ).order_by('-date_posted').exclude(author=profile.user).distinct()


class UserProjectListView(generic.ListView):
    '''User project list view'''
    model = Project
    template_name = 'user_projects.html'
    context_object_name = 'projects'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Project.objects.filter(author=user).order_by('-date_posted')


class ProjectDetailView(generic.DetailView):
    '''Project detail view'''
    model = Project
    template_name = 'project.html'


class CreatePositionView(LoginRequiredMixin, generic.CreateView):
    '''Create position view'''
    model = Position
    fields = [
        'title', 
        'content',
        'project',
        'skills'
             ]
    template_name = 'position_form.html'


class CreateProjectView(LoginRequiredMixin, generic.CreateView):
    '''Create project view'''
    model = Project
    fields = [
        'title', 
        'content', 
        'position',
        'project_timeline',
        'applicant_requirements',
             ]
    template_name = 'project_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
      

class UpdateProjectView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    '''Update project view'''
    model = Project
    fields = [
        'title', 
        'content', 
        'position',
        'project_timeline',
        'applicant_requirements',
             ]
    template_name = 'project_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.author:
            return True
        return False  


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    '''Project delete view'''
    model = Project
    template_name = 'project_confirm_delete.html'
    success_url = '/'

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.author:
            return True
        return False  


def search_projects(request):
    '''Search projects function'''
    context = {}
    input_search = request.GET.get('q')
    projects = Project.objects.filter(
        Q(title__icontains=input_search) |
        Q(content__icontains=input_search) |
        Q(position__skills__name__icontains=input_search)
    ).distinct()
    context['projects'] = projects
    return render(request, 'all_projects.html', context)    


class ApplicationListView(generic.ListView):
    '''List view of all applications, by user and by others'''
    model = Application
    template_name = 'all_applications.html'
    context_object_name = 'applications'
    ordering = ['-date_applied']
    paginate_by = 3       


class CreateApplicationView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    '''Create apply for a project view'''
    model = Application
    fields = [
        'status',
             ]
    template_name = 'application_form.html'
    success_url = '/'
    success_message = 'You have submitted your application:)'

    def form_valid(self, form):
        form.instance.applicant = self.request.user
        form.instance.project = get_object_or_404(Project, title=self.kwargs.get('slug'))
        form.instance.position = get_object_or_404(Position, id = self.kwargs.get('pk'))
        return super(CreateApplicationView, self).form_valid(form)


class UpdateApplicationView(
    LoginRequiredMixin, SuccessMessageMixin,
    UserPassesTestMixin, generic.UpdateView
     ):
    '''Update application view'''
    model = Application
    fields = [
        'status',
             ]
    template_name = 'application_status_form.html'
    success_url = '/'
    success_message = 'You have declined or accepted the application'

    def form_valid(self, form):
        form.instance.applicant = self.object.applicant
        form.instance.position = self.object.position
        position = Position.objects.get(applied_position__id=self.kwargs.get('pk'))
        if form.instance.status == 'ACC':
            position.position_status = True
            position.save()
            notify.send(
                self.request.user,
                recipient=self.object.applicant,
                verb='Your application for {} position has been accepted.'.format(
                        self.object.position,
                    )
                )
        if form.instance.status == 'DEC':   
                notify.send(
                self.request.user,
                recipient=self.object.applicant,
                verb='Your application for {} position has bee declined.'.format(
                    self.object.position
                    )
                )     
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        if self.request.user == obj.project.author:
            return True
        return False   


class UserApplicationListView(generic.ListView):
    '''List view of applications by user'''
    model = Application
    template_name = 'user_applications.html'
    context_object_name = 'applications'

    def get_queryset(self):
        user = self.request.user
        return Application.objects.filter(applicant=user).order_by('-date_applied')        


class UserProjectsApplicationsListView(generic.ListView):
    '''List view of applications for user's projects'''
    model = Application
    template_name = 'applications.html'
    context_object_name = 'my_applications'
    paginate_by = 3
    
    def get_queryset(self):
        user = self.request.user
        return Application.objects.filter(project__author=user).order_by('-date_applied')          


@login_required
def view_notifications(request):
    notifications = request.user.notifications.unread()
    return render(request, 'notifications.html',
                  {'notifications': notifications})    


        
        

my_project12_v1/projects/templates/all_applications.html
{% extends 'layout.html' %}

{% block content %}

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="applications.html">Applications</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Applications</a></li>
          {% for object in applications %}
          <li><a class="selected" >{{ object }}</a></li>
          {% endfor %}
          {% if is_paginated %}
          {% if page_obj.has_previous %}
            <a class="button icon-on-left" href="?page=1">First</a>
            <a class="button icon-on-left" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <a class="button button-primary" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
              <a class="button icon-on-left" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a class="button icon-on-left" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="button icon-on-left" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          {% endif %}

        {% endif %}

        </ul>
      </div>

  {% endblock %}

my_project12_v1/projects/templates/all_projects.html
{% extends 'layout.html' %}

{% block content %}

      <div class="circle--filter circle--secondary--module">
        <h1>All Projects</h1>
        <ul class="circle--filter--list">
          {% for object in projects %}
          <li><a class="selected" href="{% url 'projects:project_detail' pk=object.id %}" >{{ object }}</a></li>
          <li><a class="" >{{ object.content }}</a></li>
          {% for position in object.position.all %}
          <li><a class="selected>">{{ position }}</a></li>
          {% if position.position_status == False %}
          {% for skill in position.skills.all %}
          <li><a class="selected>">Skills needed currently for a project {{ skill }}</a></li>
          {% endfor %}
          {% endif %}
          {% endfor %}
          <li><a class="" href="{% url 'projects:user_list_projects' user.username %}">By: {{ object.author }}</a></li>
          {% endfor %}
          {% if is_paginated %}
            {% if page_obj.has_previous %}
              <a class="button icon-on-left" href="?page=1">First</a>
              <a class="button icon-on-left" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
                <a class="button button-primary" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <a class="button icon-on-left" href="?page={{ num }}">{{ num }}</a>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <a class="button icon-on-left" href="?page={{ page_obj.next_page_number }}">Next</a>
              <a class="button icon-on-left" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}


          {% endif %}
        </ul>
      </div>

{% endblock %}

my_project12_v1/projects/templates/application_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds">
  <div class="grid-30 centered">
  <h1>Apply for a project</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.status.as_hidden }}
    <input type="submit" value="Apply for a project" class="button-primary">
  </form>
</div>
</div>
{% endblock %}

my_project12_v1/projects/templates/application_status_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds">
  <div class="grid-30 centered">
  <h2>Update status</h2>
  <form method="POST">
    {% csrf_token %}
    <p id="status">
      <label><input type="checkbox" name="status" value="ACC"><span>Accepted</span></label>
      <label><input type="checkbox" name="status" value="DEC"><span>Declined</span></label>
    </p>
    <input type="submit" value="Save" class="button-primary">
  </form>
</div>
</div>
{% endblock %}

my_project12_v1/projects/templates/applications.html
{% extends 'layout.html' %}

{% block content %}

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="applications.html">Applications</a></li>
        <li><a href="{% url 'projects:recom_list_projects' %}">Projects for you ❀</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Applications</a></li>
          {% for object in my_applications %}
            {% if object.status == 'AWA' %}
              <li><a>{{ object }}</a></li>
                <a class="button button-outline" href="{% url 'projects:application_update' object.id %}">Update status</a>
            {% endif %}    
            {% endfor %}
            <li><a class="selected">New Applications</a></li>
            <li><a class="selected">Accepted</a></li>
            {% for object in my_applications %}
            {% if object.status == 'ACC' %}
              <li><a>{{ object }}</a></li>
            {% endif %}
            {% endfor %}
            <li><a class="selected">Rejected</a></li>
            {% for object in my_applications %}
            {% if object.status == 'DEC' %}
              <li><a>{{ object }}</a></li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Projects</a></li>
          <li><a>Currency Calculator</a></li>
          <li><a>Twitter Client</a></li>
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Needs</a></li>
          <li><a>Android Developer</a></li>
          <li><a>Designer</a></li>
          <li><a>Java Developer</a></li>
          <li><a>PHP Developer</a></li>
          <li><a>Python Developer</a></li>
          <li><a>Rails Developer</a></li>
          <li><a>WordPress Developer</a></li>
          <li><a>iOS Developer</a></li>
        </ul>
      </div>

    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
          </tr>
        </thead>
        <tbody>
          <tr class="clickable-row" data-href="profile.html">
            <td>
              <h3>Jim Horton</h3>
              <p>Currency Calculator</p>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Rails Developer</span>
            </td>
          </tr>
          <tr class="clickable-row" data-href="profile.html">
            <td>
              <h3>Jenny McMann</h3>
              <p>Currency Calculator</p>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">Designer</span>
            </td>
          </tr>
        </tbody>
      </table>

    </div>

  </div>

  
  {% endblock %}

my_project12_v1/projects/templates/notifications.html
{% extends 'layout.html' %}

{% block content %}

<div class="bounds">
  <div class="grid-30 centered">
    <h1>Notifications</h1>
      {% if notifications %}
        {% for object in notifications %}
          <h2>{{ object.verb }}</h2>
          {% endfor %}
        {% endif %}
      <div class="border-top pt-3">
      </div>
  </div>
</div>

{% endblock %}

my_project12_v1/projects/templates/position_form.html
{% extends 'layout.html' %}

{% block content %}

<div class="bounds">
  <div class="grid-30 centered">
  <h1>Position</h1>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create Position" class="button-primary">
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Do you have an account already?<a class="ml-2" href="#">Log In</a>
      </small>
    </div>
  </div>
</div>

{% endblock %}

my_project12_v1/projects/templates/project.html
{% extends 'layout.html' %}

{% block content %}

  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        {% if object.author == user %}
          <a class="button" href="{% url 'projects:project_update' object.id %}">Edit Project</a>
          <a class="button button-text" href="{% url 'projects:project_delete' object.id %}">Delete Project</a>
          <a class="button button-text" href="{% url 'projects:position_create' %}">Create Position</a>
        {% endif %}  
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ object.title }}</h1>
        <p class="circle--article--byline" >Project Owner: <a href="{% url 'projects:user_list_projects' object.author.username %}">{{ object.author }}</a></p>
      </div>

      <div class="circle--article--body">
        <p>{{ object.content }}</p>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>
        <ul class="circle--group--list">
          {% if user != project.author %}
            {% for position in project.position.all %}
            <li>
              <h3>{{ position }}</h3>
              <a class="button button-primary" href="{% url 'projects:application_create' slug=project.title pk=position.id %}">Apply</a>
            </li>
            {% endfor %}
          {% endif %}
          {% if user == project.author %}
            {% for position in project.position.all %}
            <li>
              <h3>{{ position }}</h3>
            </li>
            {% endfor %}
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <h3>Project Needs</h3>
        {% for position in project.position.all %}
        {% if position.position_status == True %}
        <ul class="circle--link--list">
          <li><a>{{ position }} is already filled</a></li>
        </ul>
        {% else %}
        <ul class="circle--link--list">
          <li><a>Required: {{ position }} </a></li>
        </ul>
        {% endif %}
        {% endfor %}
      </div>

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ object.project_timeline }}</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <p>{{ object.applicant_requirements }}</p>
      </div>

    </div>
  </div>

{% endblock %}

my_project12_v1/projects/templates/project_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}

<div class="bounds">
  <div class="grid-30 centered">
  <h1>Project</h1>
    <form method="POST">
      {% csrf_token %}
      <h2>Do you want to delete this '{{ object.title }}' project?</h2>
      <input type="submit" value="Delete Project" class="button-primary">
      <a class="button-secondary" href="{% url 'projects:project_detail' object.id %}">Cancel</a>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Do you have an account already?<a class="ml-2" href="#">Log In</a>
      </small>
    </div>
  </div>
</div>

{% endblock %}

my_project12_v1/projects/templates/project_form.html
{% extends 'layout.html' %}

{% block content %}

<div class="bounds">
  <div class="grid-30 centered">
  <h1>Project</h1>
    <form method="POST">
      {% csrf_token %}
      <label>Title</label>
      {{ form.title }}
      <label>Content</label>
      {{ form.content }}
      <label>Project Timeline</label>
      {{ form.project_timeline }}
      <label>Project Position</label>
      {{ form.position }}
      <label>Applicant Requirements</label>
      {{ form.applicant_requirements }}
      <input type="submit" value="Create Project" class="button-primary">
    </form>
    
    <div class="border-top pt-3">
      <small class="text-muted">
        Do you have an account already?<a class="ml-2" href="#">Log In</a>
      </small>
    </div>
  </div>
</div>

{% endblock %}

my_project12_v1/projects/templates/recom_projects.html
{% extends 'layout.html' %}

{% block content %}

<div class="circle--actions--bar">
  <nav class="bounds">
    <ul class="circle--pill--list">
      <li><a class="selected" href="{% url 'projects:recom_list_projects' %}">Projects for you ❀</a></li>
      <li><a href="{% url 'projects:applications' pk=user.id %}">Applications</a></li>
      <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
    </ul>
  </nav>
</div>
      <div class="circle--filter circle--secondary--module">
        <h1>All Projects</h1>
        <ul class="circle--filter--list">
            {% for object in recom_projects %}
              {% for position in object.position.all %}
                {% if position.position_status == False %}
                  <li><a class="selected" >{{ object }}</a></li>
                  <li><a class="" >{{ object.content }}</a></li>
                  <li><a class="selected>">{{ position }}</a></li>
                  {% for skill in position.skills.all %}
                  <li><a class="selected>">Skills needed currently for a project {{ skill }}</a></li>
                  <li><a class="" href="{% url 'projects:user_list_projects' user.username %}">By: {{ object.author }}</a></li>
                  {% endfor %}
                {% endif %}
              {% endfor %}
            {% endfor %}
          {% if is_paginated %}
            {% if page_obj.has_previous %}
              <a class="button icon-on-left" href="?page=1">First</a>
              <a class="button icon-on-left" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
                <a class="button button-primary" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <a class="button icon-on-left" href="?page={{ num }}">{{ num }}</a>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <a class="button icon-on-left" href="?page={{ page_obj.next_page_number }}">Next</a>
              <a class="button icon-on-left" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

          {% endif %}
        </ul>
      </div>

{% endblock %}

my_project12_v1/projects/templates/user_applications.html
{% extends 'layout.html' %}

{% block content %}

<h1>Applications by {{ user }} </h1>

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="applications.html">Applications</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">User Applications</a></li>
          {% for object in applications %}
            <li><a class="selected" >{{ object }}</a></li>
          {% endfor %}
            <li><a class="selected">Accepted</a></li>
            {% for object in applications %}
              {% if object.status == 'ACC' %}
                <li><a>{{ object }}</a></li>
              {% endif %}
            {% endfor %}
            <li><a class="selected">Rejected</a></li>
            {% for object in applications %}
              {% if object.status == 'DEC' %}
                <li><a>{{ object }}</a></li>
              {% endif %}
            {% endfor %}
        </ul>
      </div>

  {% endblock %}