my_project12_v1/accounts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import (ChangeProfileView, LoginView, LogoutView, SignupView,
                    profile)

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='blog-home'),
    path("login/", LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/<pk>/', ChangeProfileView.as_view(), name='profile_update'),
]

my_project12_v1/my_project12_v1/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

my_project12_v1/projects/urls.py
from django.urls import path

from . import views
from .views import (ApplicationListView, CreateApplicationView,
                    CreateProjectView, ProjectDeleteView, ProjectDetailView,
                    ProjectListView, RecomProjectListView,
                    UpdateApplicationView, UpdateProjectView,
                    UserApplicationListView, UserProjectListView,
                    UserProjectsApplicationsListView,
                    CreatePositionView,
                    )

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='list_projects'),
    path('recom/', RecomProjectListView.as_view(), name='recom_list_projects'),
    path('user/<str:username>/', UserProjectListView.as_view(), name='user_list_projects'),
    path('project/new/', CreateProjectView.as_view(), name='project_create'),
    path('position/new/', CreatePositionView.as_view(), name='position_create'),
    path('project/<pk>/update/', UpdateProjectView.as_view(), name='project_update'),
    path('project/<pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('search/', views.search_projects, name='project_search'),
    path('applications/all/', ApplicationListView.as_view(), name='list_applications'),
    path('applications/new/<slug>/<pk>/', CreateApplicationView.as_view(), name='application_create'),
    path('applications/user/<pk>/', UserApplicationListView.as_view(), name='user_list_applications'),
    path('applications/touser/<pk>/', UserProjectsApplicationsListView.as_view(), name='applications'),
    path('applications/status/update/<pk>/', UpdateApplicationView.as_view(), name='application_update'),
    path('applications/notifications/', views.view_notifications, name="notifications"),
]

my_project12_v1/accounts/models.py
from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin, User)
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image

from projects.models import Application


class UserManager(BaseUserManager):

    def create_user(self, email, username, display_name=None, password=None):
        if not email:
            raise ValueError("You should enter an email address")
        if not display_name:
            display_name = username

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            display_name=display_name
        )    
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, display_name, password):
        user = self.create_user(
            email,
            username,
            display_name,
            password
        )    
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    '''A user model'''
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)
    display_name = models.CharField(max_length=140)
    bio = models.CharField(max_length=140, blank=True, default='')
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    avatar = models.ImageField(default='default.png', upload_to='profile_pics')
    skills = models.ManyToManyField('Skill')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['display_name', 'username']

    def __str__(self):
        return self.username

    def get_short_name(self):
        return self.display_name

    @property
    def is_admin(self):
        return self.is_staff


class Skill(models.Model):
    '''A model for skills'''
    JS = 'JavaScript'
    SQL = 'SQL'
    PYTHON = 'Python'  
    CSS = 'CSS'  
    DESIGN = 'Design'
    UX = 'UX'
    SKILLS_LIST = (
        (JS , "JavaScript"),
        (SQL , "SQL Databases"),
        (PYTHON, "Python"),
        (CSS, 'CSS'),
        (DESIGN, 'Design'),
        (UX, 'User experience'),
    )

    name = models.CharField(choices=SKILLS_LIST, max_length=10, default=JS)

    def __str__(self):
        return self.name.title()
 
      
class Profile(models.Model):
    '''Profile model'''
    user = models.OneToOneField(
        User, 
        on_delete = models.CASCADE,

    )
    bio = models.CharField(max_length=140, blank=True, default='')
    avatar = models.ImageField(default='default.png', upload_to='profile_pics')
    skills = models.ManyToManyField(Skill)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()  

        img = Image.open(self.avatar.path)  

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)        

my_project12_v1/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile, Skill


class UserCreateForm(UserCreationForm):
    '''User creation form'''
    class Meta:
        fields = (
            'username', 'email', 'password1', 'password2'
        )
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display name'
        self.fields['email'].label = 'Email address'    


class UserUpdateForm(forms.ModelForm):
    '''User update form'''
    class Meta:
        fields = (
            'username', 'email',
        )
        model = get_user_model()


class ProfileUpdateForm(forms.ModelForm):
    '''Profile update form'''    
    class Meta:
        model = Profile  
        fields = (
            'avatar',
            'bio',
        )  

my_project12_v1/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic

from projects.models import Application, Project

from . import forms
from .models import Profile, User, UserManager


def home(request):
    return render(request, 'accounts/profile_edit.html')


class LoginView(generic.FormView):
    '''Login view'''
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/login.html'

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())    

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


class LogoutView(generic.RedirectView):
    '''Log out view'''
    url = reverse_lazy('home')
    
    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class SignupView(SuccessMessageMixin, generic.CreateView):
    '''Sign up view'''
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/signup.html'
    success_message = "You've been signed up and you can login now :)"
    

class ChangeProfileView(LoginRequiredMixin, generic.UpdateView):
    '''Update profile view'''
    model = Profile
    fields = ['avatar', 'bio', 'skills']
    template_name = 'accounts/profile_edit.html'
    success_url = reverse_lazy('accounts:profile')

    def test_func(self):
        obj = self.get_object()
        user = self.request.user
        if obj == user:
            return True
        else:
            raise Http404('Sorry, You can not update this profile')    


class ProfileView(LoginRequiredMixin, generic.DetailView):
    '''Profile view'''
    model = Profile
    template_name = 'accounts/profile.html'
    

@login_required
def profile(request):
    if request.method == 'POST':
        user_update_form = forms.UserUpdateForm(
            request.POST, 
            instance=request.user)
        profile_update_form = forms.ProfileUpdateForm(
            request.POST, 
            request.FILES,
            instance=request.user.profile)
        if user_update_form.is_valid() and profile_update_form.is_valid():
            user_update_form.save()
            profile_update_form.save()
            return redirect('accounts:profile')
    else:
        user_update_form = forms.UserUpdateForm(instance=request.user)
        profile_update_form = forms.ProfileUpdateForm(instance=request.user.profile)
    profile = request.user.profile    
    skills = profile.skills.all()   
    user_projects = Project.objects.filter(
            author = request.user)        
    data = {
        'user_update_form': user_update_form,
        'profile_update_form': profile_update_form,
        'skills': skills,
        'user_projects': user_projects,
        'profile': profile,
    }

    return render(request, 'accounts/profile.html', data)    

my_project12_v1/accounts/templates/accounts/login.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds">
  <div class="grid-30 centered">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login" class="button-primary">
  </form>
  <div class="border-top pt-3">
    <small class="text-muted">
      Do you want to register?<a class="ml-2" href="{% url 'accounts:signup' %}">Sign Up</a>
    </small>
  </div>
</div>
</div>
{% endblock %}

my_project12_v1/accounts/templates/accounts/profile.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:recom_list_projects' %}">Projects for you ❀</a></li>
        <li><a href="{% url 'projects:applications' pk=user.id %}">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>{{ user.username }}</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button icon-on-left" href="{% url 'accounts:profile_update' pk=user.id  %}">Edit</a>
      </div>
    </div>

    <div class="grid-70">
      <h1>{{ user.username }}</h1>
      <div class="circle--article--body">
        <p>{{ profile.bio }}</p>
      </div>

      <h2>Past Projects</h2>
      <ul>
        <li><a class="selected">Coming soon</a></li>
        {% for object in user_applics %}
        <li><a class="selected">{{ object }}</a></li>
        {% endfor %}
      </ul>
        <thead>

        </thead>

      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <img class="circle--primary--avatar" src="{{ user.profile.avatar.url }}">
      </div>

    <!--Skills -->

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="unloaded">
          {% for skill in skills %}
            <li>
              {{ skill }}
            </li>
          {% endfor %}
        </ul>
      </div>



      <div class="circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--link--list">
          {% for object in user_projects %}
          <li><a class="selected" href="{% url 'projects:project_detail' pk=object.id %}">{{ object }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

  {% endblock %}

my_project12_v1/accounts/templates/accounts/profile_edit.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="applications.html">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>{{ user.username }}</h2>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <div class="circle--secondary--module">
            <img class="circle--primary--avatar" src="{{ user.profile.avatar.url }}">
          </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            {{ form.as_p }}
            {{ user_update_form }}
            {{ profile_update_form }}
              <input type="submit" value="Update Account" class="button-primary">
        </form>
      </div>
    </div>

    {% endblock %}

my_project12_v1/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<div class="bounds">
  <div class="grid-30 centered">
  <h1>SignUp</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Signup" class="button-primary">
  </form>
  <div class="border-top pt-3">
    <small class="text-muted">
      Do you have an account already?<a class="ml-2" href="{% url 'accounts:login' %}">Log In</a>
    </small>
  </div>
</div>
</div>
{% endblock %}